# theme = "darcula"
# theme = "onelight"
theme = "term16_dark"

[editor]
line-number = "relative"
auto-pairs = false # defaults to `true`
rulers = [100]

[editor.file-picker]
git-ignore = false

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = false

[editor.statusline]
left = ["mode",
        "spinner"]
center = ["version-control",
          "file-name"]
right = ["diagnostics",
         "selections",
         "position",
         "position-percentage",
         "file-encoding",
         "file-line-ending",
         "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"

[keys.normal.space.t]
"1" = ":theme term16_light"
"2" = ":theme term16_dark"
